package com.edutech.edutechbackend.entity;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "subjects")
@Getter @Setter
@NoArgsConstructor @AllArgsConstructor
@Builder
public class Subject {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    // ↑ auto-generated by DB
    //   1, 2, 3, 4... increases automatically
    //   we never set this manually

    @Column(nullable = false, unique = true)
    private String name;
    // ↑ "Math", "Science", "English"
    //   unique = true → can't have two subjects both named "Math"
    //   nullable = false → name is required, can't be empty
}