package com.edutech.edutechbackend.service;


import com.edutech.edutechbackend.dto.AuthResponseDTO;
import com.edutech.edutechbackend.dto.LoginRequestDTO;
import com.edutech.edutechbackend.dto.RegisterRequestDTO;
import com.edutech.edutechbackend.entity.Student;
import com.edutech.edutechbackend.exception.EmailAlreadyExistsException;
import com.edutech.edutechbackend.exception.InvalidCredentialsException;
import com.edutech.edutechbackend.repository.StudentRepository;
import com.edutech.edutechbackend.util.JwtUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.BadCredentialsException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
// ↑ marks this as a Spring service bean
//   Spring manages its lifecycle
//   can be @Autowired / injected anywhere

@RequiredArgsConstructor
// ↑ Lombok generates constructor for all final fields
//   Spring injects all dependencies through this constructor
public class AuthService {

    private final StudentRepository studentRepository;
    // ↑ to: check email exists, save student, find by email

    private final PasswordEncoder passwordEncoder;
    // ↑ to: encode raw password before saving
    //   BCryptPasswordEncoder from SecurityConfig

    private final AuthenticationManager authenticationManager;
    // ↑ to: verify email + password during login
    //   configured in SecurityConfig
    //   delegates to DaoAuthenticationProvider

    private final JwtUtil jwtUtil;
    // ↑ to: generate JWT token after successful auth

    // ════════════════════════════════════════════════════════════
    // REGISTER
    // ════════════════════════════════════════════════════════════
    @Transactional
    // ↑ wraps this method in a database transaction
    //   if anything fails → all DB changes rolled back
    //   ensures data consistency
    public AuthResponseDTO register(RegisterRequestDTO request) {

        // ── STEP 1: Check if email already exists ─────────────────────────
        if (studentRepository.existsByEmail(request.getEmail())) {
            // existsByEmail() → SELECT COUNT(*) FROM students WHERE email = ?
            // returns true if student with this email already exists
            throw new EmailAlreadyExistsException(
                    "Email already registered: " + request.getEmail()
            );
            // ↑ throws our custom exception
            //   Spring will catch this in global exception handler
            //   returns 409 Conflict to client
            //   method stops here — nothing below runs
        }

        // ── STEP 2: Encode the password ───────────────────────────────────
        String encodedPassword = passwordEncoder.encode(request.getPassword());
        // passwordEncoder = BCryptPasswordEncoder(10)
        // .encode("mypassword123")
        // → runs BCrypt hashing algorithm with salt
        // → returns "$2a$10$randomSalt+hashedResult"
        // → DIFFERENT hash every time even for same password (because random salt)
        // → this is what gets stored in DB, NEVER the raw password

        // ── STEP 3: Build Student entity ──────────────────────────────────
        Student student = Student.builder()
                .name(request.getName())
                // ↑ "John Doe" from request

                .email(request.getEmail())
                // ↑ "john@gmail.com" from request

                .password(encodedPassword)
                // ↑ "$2a$10$xyz..." — NEVER store raw password
                // createdAt is set automatically by @PrePersist in Student entity

                .gender(request.getGender())
                // ↑ Gender enum from request
                //   e.g. Gender.MALE
                .dateOfBirth(request.getDateOfBirth())
                // ↑ LocalDate from request
                //   e.g. 2000-05-15

                .role(request.getRole())

                .build();
        // ↑ @Builder from Lombok lets us use this clean builder pattern
        //   instead of: Student s = new Student(); s.setName("John"); etc.

        // ── STEP 4: Save to PostgreSQL ────────────────────────────────────
        Student savedStudent = studentRepository.save(student);
        // .save() → INSERT INTO students (name, email, password, created_at)
        //           VALUES (?, ?, ?, ?)
        // returns the saved student WITH the generated id
        // savedStudent.getId() → 1 (auto-generated by DB)

        // ── STEP 5: Generate JWT token ────────────────────────────────────
        String token = jwtUtil.generateToken(student.getEmail(), student.getRole().name());
        // generateToken(email):
        //   → builds JWT with email as "sub" claim
        //   → sets expiry to 24 hours from now
        //   → signs with HMAC-SHA256 using our secret key
        //   → returns "eyJhbGciOiJIUzI1NiJ9.xxx.yyy"

        // ── STEP 6: Build and return response ────────────────────────────
        return AuthResponseDTO.builder()
                .token(token)
                // ↑ the JWT token — client stores this
                //   sends it in Authorization header for future requests

                .name(savedStudent.getName())
                // ↑ "John Doe" — for displaying in UI

                .email(savedStudent.getEmail())
                // ↑ "john@gmail.com"

                .role(student.getRole().name())

                .message("Registration successful")
                // ↑ human readable success message

                .build();
        // this DTO is returned to AuthController
        // AuthController returns it as JSON response with 201 Created
    }

    // ════════════════════════════════════════════════════════════
    // LOGIN
    // ════════════════════════════════════════════════════════════
    public AuthResponseDTO login(LoginRequestDTO request) {

        // ── STEP 1: Verify credentials ────────────────────────────────────
        try {
            authenticationManager.authenticate(
                    new UsernamePasswordAuthenticationToken(
                            request.getEmail(),
                            // ↑ the email student typed in login form

                            request.getPassword()
                            // ↑ the RAW password student typed
                            //   AuthenticationManager will:
                            //     → call loadUserByUsername(email)
                            //       → hit DB → find Student → convert to UserDetails
                            //     → call BCrypt.matches(rawPassword, storedHash)
                            //       → compares what student typed with what's in DB
                    )
            );
            // ↑ if this line completes without exception → credentials correct ✅
            // ↑ if wrong password → throws BadCredentialsException
            // ↑ if email not found → throws UsernameNotFoundException
            //   (from CustomUserDetailsService)

        } catch (BadCredentialsException e) {
            // BadCredentialsException = wrong password OR email not found
            // we catch it and throw our own cleaner exception
            throw new InvalidCredentialsException("Invalid email or password");
            // ↑ vague message intentionally — security best practice
            //   don't tell attacker whether email exists or password is wrong
            //   "Invalid email or password" tells them nothing useful
        }

        // ── STEP 2: Load student from DB ──────────────────────────────────
        // we reach here ONLY if authentication above was successful
        Student student = studentRepository.findByEmail(request.getEmail())
                .orElseThrow(() ->
                        new InvalidCredentialsException("Invalid email or password")
                );
        // ↑ we need the Student object to get name for the response DTO
        //   authentication already passed so this student DEFINITELY exists
        //   the orElseThrow is just a safety net — should never trigger here

        // ── STEP 3: Generate JWT token ────────────────────────────────────
        String token = jwtUtil.generateToken(student.getEmail(), student.getRole().name());
        // same as registration:
        //   → builds JWT with email in payload
        //   → signs with secret key
        //   → returns token string

        // ── STEP 4: Build and return response ────────────────────────────
        return AuthResponseDTO.builder()
                .token(token)
                .name(student.getName())
                .email(student.getEmail())
                .role(student.getRole().name())
                .message("Login successful")
                .build();
        // returned to AuthController
        // AuthController returns as JSON with 200 OK
    }
}